FROM phpdockerio/nginx:latest

ADD . /var/www/html
ADD ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR "/var/www/html"
VOLUME ["/var/www/html/web/app/uploads", "/var/log/nginx/"]

EXPOSE 80
