nginx:
  image: phpdockerio/nginx:latest
  container_name: wpw-nginx
  volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - php-fpm

php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: wpw-fpm
  volumes:
    - .:/var/www/html
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
  environment:
    WP_ENV: development
    WP_HOME: "http://local.rafagnin.com:8080"
    WP_SITEURL: "http://local.rafagnin.com:8080/wp"
    DB_NAME: wpwdb
    DB_USER: wpw
    DB_PASSWORD: password
    DB_HOST: mysql
    AUTH_KEY: '?E><!}A/#.s<=6n6YQMnnmSz-S.)|rA<Mas|WC^W7@dW2NwaQE,iUnVo:D^E?PVQ'
    SECURE_AUTH_KEY: 'MQJRXF*u3V^Ld/xV}n$$|0w@NBgh;EQol9dj&W`b<okXNg$$0/MgB_r!k=b0l)Q!=='
    LOGGED_IN_KEY: 'JZFx$$`,axe<<JAn=1hP=7R@NPDi5(H.ZGyB3GP6Pj>d*C7zsOO8x@!X2a.udj^qP'
    NONCE_KEY: 'cC_Lzd>hT|,F4@jn{jRMIipZ44K`2VB[nrWr7+pTzaPP]&)^&Fd|q8?yU,.#oL?J'
    AUTH_SALT: 'xp)[,0x83X&H`oyY9fTM_u1D#ycY@sAcxs?+M&5``{mSmy.#L)bW(w4j?Fkvcl]*'
    SECURE_AUTH_SALT: 'qWj`G]?_(n_giz8qjEo#)xK^QE4P.-&tZA{|vrLL/jIoJ,,mLGz8l&3V#D3:J;A,'
    LOGGED_IN_SALT: ':>J+vCpy$$)VSjCMaNTs&-dLVuWwvC|Y7*Cy9M[r8h,{!MLdch&dmb9[Py]eooVi}'
    NONCE_SALT: 'T*OQ;Z0;0$$Q.-L;uop`oh4Q9o0,9Ez85fU4rfZ:ZTuCjy4Ah$$MhYDdv,ReBwI@x:'
    DISABLE_WP_CRON: "true"
  extra_hosts:
    - mysqlhost:192.168.2.76
  links:
    - mysql

mysql:
  image: mysql:latest
  container_name: wpw-mysql
  volumes:
    - ./mysql_data:/var/lib/mysql
  ports:
   - "5000:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: wpw
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: wpwdb
